name: JS Actions

# on: [push]

on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: hello-action
        uses: ./.github/actions/hello-world
        # with:
        #   third-greeting: "Learning Lab User"

      - name: ha-ha
        uses: ./.github/actions/joke-action